pr: none
trigger:
  branches: 
   include:
     - main
     - dev

pool: Ashu-pool

variables:
  Work_Dir: '$(System.DefaultWorkingDirectory)/environments/dev'


stages:
  - stage: INIT
    displayName: init and tool installer
    jobs: 
    - job: tool_install
      steps:
      - task: TerraformInstaller@1
        displayName: tool install
        inputs:
          terraformVersion: 'latest'

    - template: templates.yml

  - stage: Manual_approval
    pool: server
    dependsOn: INIT
    jobs:
      - job: Manual_approval
        steps: 
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'ashutosh.pal26@outlook.com'
            approvers: 'ashutosh.pal26@outlook.com'


  
  - stage: Apply
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main') 
    dependsOn: Manual_approval
    jobs: 
    - job: Apply
      steps:
      - task: TerraformTask@5
        displayName: Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: $(Work_Dir)
          backendServiceArm: 'Ashu-svc'
          backendAzureRmStorageAccountName: 'stg13example'
          backendAzureRmContainerName: 'pravin'
          backendAzureRmKey: 'pravinn.tfstate'

      - task: TerraformTask@5
        displayName: Apply_wali_job
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: $(Work_Dir)
          environmentServiceNameAzureRM: 'Ashu-svc'