trigger: none

pool: Ashu-pool

variables:
  Work_Dir: '$(System.DefaultWorkingDirectory)/environments/dev'


stages:
  - stage: INIT
    displayName: init and tool installer
    jobs: 
    - job: tool_install
      steps:
      - task: TerraformInstaller@1
        displayName: tool install
        inputs:
          terraformVersion: 'latest'

    - job: init_and_plan
      steps:
      - task: TerraformTask@5
        displayName: init wala task
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: $(Work_Dir)
          backendServiceArm: 'Ashu-svc'
          backendAzureRmStorageAccountName: 'stg13example'
          backendAzureRmContainerName: 'pravin'
          backendAzureRmKey: 'pravinn.tfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: $(Work_Dir)
          environmentServiceNameAzureRM: 'Ashu-svc'

    - job: Manua_approval
      dependsOn: init_and_plan
      pool: server
      steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'Ashutosh.pal26@outlook.com'
          approvers: 'Ashutosh.pal26@outlook.com'

  
  - stage: Apply
    dependsOn: INIT
    jobs: 
    - job: Apply
      steps:
      - task: TerraformTask@5
        displayName: Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: $(Work_Dir)
          backendServiceArm: 'Ashu-svc'
          backendAzureRmStorageAccountName: 'stg13example'
          backendAzureRmContainerName: 'pravin'
          backendAzureRmKey: 'pravinn.tfstate'

      - task: TerraformTask@5
        displayName: Apply_wali_job
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: $(Work_Dir)
          environmentServiceNameAzureRM: 'Ashu-svc'